### ISSUE TITLE
Can you provide right status code for create action

### ISSUE THREAD

**Issue by gavaig** [slavkoBV/ToDo-app-Sanic#2]
https://github.com/slavkoBV/ToDo-app-Sanic/blob/fc298e2d12b0b2c925bbfd5804a1eccd67a73293/app.py#L54

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201

**Comment by slavkoBV** [comment]
Status code was changed to 201. Thank you
